In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats.stats import pearsonr
import numpy as np
#from sklearn.model_selection import train_test_split
#from sklearn import preprocessing
#from sklearn.linear_model import LogisticRegression
import scipy.stats as st
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [2]:
raw_data= pd.read_csv('hlc_all_metrics_new_upd_final_1.csv')

FileNotFoundError: [Errno 2] File b'hlc_all_metrics_new_upd_final_1.csv' does not exist: b'hlc_all_metrics_new_upd_final_1.csv'

In [39]:
#raw_data['high_ltr'] = np.where(raw_data['decile_rank_last_1_yr_upd'] == 1, 1, 0)

In [66]:
raw_data.head()

email_acq     fp_home       fp_ov  decile_rank  time_bn_wm_and_home  no_items_lt  auth_revenue_lt  no_divisions_lt  auth_qty_lt  no_items_lt_baby  auth_revenue_lt_baby  no_depts_lt_baby  auth_qty_lt_baby  no_items_lt_edl  auth_revenue_lt_edl  no_super_depts_lt_edl  auth_qty_lt_edl      aov_wm  ent_aov  enp_aov  edl_aov  fashion_aov  baby_care_and_safety_aov  baby_consumables_aov  baby_misc_aov  nursery_aov  avg_wm_order_gap  avg_ent_order_gap  avg_enp_order_gap  avg_edl_order_gap  avg_fashion_order_gap  avg_baby_order_gap  avg_baby_care_and_safety_order_gap  avg_baby_consumables_order_gap  avg_baby_gear_order_gap  avg_baby_misc_order_gap  avg_nursery_order_gap  accessories_and_travel_aov  automotive_parts_and_accessories_aov  baby_aov  childrens_apparel_aov  electronics_aov  fashion_misc_l1_aov  footwear_aov  grocery_and_wholesale_aov  health_beauty_and_wellness_aov  home_improvement_aov  household_and_personal_care_aov  jewelry_and_watches_aov  mens_apparel_aov  \
0  1000134159885214  2018-04-19  2008-11-23           14           114.433333            1             6.99                1            1               NaN                   NaN               NaN               NaN              NaN                  NaN                    NaN              NaN  129.983333  191.480     6.99      NaN          NaN                       NaN                   NaN            NaN          NaN               4.0                6.0               12.0                NaN                    NaN                 NaN                                 NaN                             NaN                      NaN                      NaN                    NaN                         NaN                                   NaN       NaN                    NaN              NaN                  NaN           NaN                        NaN                             NaN                   NaN                              NaN                      NaN               NaN   
1  100075EAC6F1B82B  2018-04-01  2016-11-14           49            16.733333            3            39.76                1            3               NaN                   NaN               NaN               NaN              NaN                  NaN                    NaN              NaN   39.760000      NaN      NaN      NaN        39.76                       NaN                   NaN            NaN          NaN              12.0                NaN                NaN                NaN                   12.0                 NaN                                 NaN                             NaN                      NaN                      NaN                    NaN                         NaN                                   NaN       NaN                  39.76              NaN                  NaN           NaN                        NaN                             NaN                   NaN                              NaN                      NaN               NaN   
2  1000A54BB51EBB0F  2018-03-02  2014-05-30           47            45.733333            1           159.00                1            1               NaN                   NaN               NaN               NaN              NaN                  NaN                    NaN              NaN  159.000000  159.000      NaN      NaN          NaN                       NaN                   NaN            NaN          NaN              12.0               12.0                NaN                NaN                    NaN                 NaN                                 NaN                             NaN                      NaN                      NaN                    NaN                         NaN                                   NaN       NaN                    NaN            159.0                  NaN           NaN                        NaN                             NaN                   NaN                              NaN                      NaN               NaN   
3  1000EA46ABBD6EE9  2018-03-23  2015-11-27       

In [67]:
correlation_matrix = raw_data.corr(method='pearson',min_periods=1)

In [44]:
correlation_matrix.to_excel('Correlation_matrix.xlsx')

In [47]:
#raw_data.count()
raw_data.isnull().sum().to_excel('Number_of_nulls.xlsx')

In [76]:
data_with_sel_cols = raw_data[['email_acq','time_bn_wm_and_home','no_items_lt','auth_revenue_lt','no_items_lt_edl','aov_wm','ent_aov','enp_aov','fashion_aov',
             'avg_wm_order_gap','first_order_wm_gmv','holiday_gmv','non_holiday_gmv','avg_basket_value_delta','no_home_visits',
             'no_home_page_views','no_divisions_per_order','top_brand_revenue_percent','avg_dwell_time', 'gender', 'age_group', 'income_group', 
                       'hh_adult_qty', 'hh_children_qty', 'ethnicity', 'urbanicity', 'marital_status_cd', 'wm_pdp_visits', 'decile_rank_last_1_yr', 'auth_revenue']]

# Checking Outliers

In [77]:
data_with_sel_cols.isnull().sum()

email_acq                         0
time_bn_wm_and_home               0
no_items_lt                       0
auth_revenue_lt                   0
no_items_lt_edl              213588
aov_wm                            0
ent_aov                      138932
enp_aov                      255696
fashion_aov                  265214
avg_wm_order_gap                  0
first_order_wm_gmv                0
holiday_gmv                  197603
non_holiday_gmv               61033
avg_basket_value_delta       235570
no_home_visits                27094
no_home_page_views            27094
no_divisions_per_order            0
top_brand_revenue_percent    273102
avg_dwell_time                27094
gender                        77880
age_group                     77874
income_group                  77874
hh_adult_qty                  78309
hh_children_qty               77928
ethnicity                     77874
urbanicity                    78032
marital_status_cd             78029
wm_pdp_visits               

In [78]:
data_with_sel_cols1 = data_with_sel_cols.fillna('NULL')
data_with_sel_cols1.to_excel('Raw_data_with_selected_columns1.xlsx')

In [72]:
raw_data_imputed = pd.read_csv('Raw_data_with_selected_columns1_imputed.csv')

In [3]:
# importing one hot encoder from sklearn 
#import sklearn
from sklearn.preprocessing import MultiLabelBinarizer

# SPLIT DATA 70:30

In [54]:
x_train, x_test, y_train, y_test= train_test_split(final_data.drop(['high_ltr'], axis= 1), final_data['high_ltr'], test_size=0.3)

In [57]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(final_data1.drop(['high_ltr'], axis= 1), final_data1['high_ltr'], test_size=0.3)

# Logistic Regression

In [58]:
from sklearn.linear_model import LogisticRegression
logistic= LogisticRegression()
logistic.fit(x_train, y_train)
logistic_prediction= logistic.predict(x_test)

In [59]:
from sklearn.linear_model import LogisticRegression
logistic= LogisticRegression()
logistic.fit(x_train1, y_train1)
logistic_prediction= logistic.predict(x_test1)

In [60]:
from sklearn.metrics import classification_report
from sklearn import metrics
print(classification_report(y_test,logistic_prediction))
print("Accuracy:",metrics.accuracy_score(y_test, logistic_prediction))
metrics.confusion_matrix(y_test, logistic_prediction)

             precision    recall  f1-score   support

          0       0.67      0.94      0.78     75803
          1       0.34      0.06      0.10     37493

avg / total       0.56      0.65      0.56    113296

Accuracy: 0.6503936590876995


array([[71469,  4334],
       [35275,  2218]], dtype=int64)

In [61]:
from sklearn.metrics import classification_report
from sklearn import metrics
print(classification_report(y_test1,logistic_prediction))
print("Accuracy:",metrics.accuracy_score(y_test1, logistic_prediction))
metrics.confusion_matrix(y_test1, logistic_prediction)

             precision    recall  f1-score   support

          0       0.69      0.97      0.80     75935
          1       0.60      0.11      0.18     37361

avg / total       0.66      0.68      0.60    113296

Accuracy: 0.6817981217342183


array([[73314,  2621],
       [33430,  3931]], dtype=int64)

# K- NN

In [62]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
knn.fit(x_train, y_train)
knn_prediction= knn.predict(x_test)

In [64]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
knn.fit(x_train1, y_train1)
knn_prediction= knn.predict(x_test1)

In [63]:
print(classification_report(y_test,knn_prediction))
print("Accuracy:",metrics.accuracy_score(y_test, knn_prediction))
metrics.confusion_matrix(y_test, knn_prediction)

             precision    recall  f1-score   support

          0       0.68      0.81      0.74     75803
          1       0.38      0.23      0.29     37493

avg / total       0.58      0.62      0.59    113296

Accuracy: 0.6223167631690439


array([[61762, 14041],
       [28749,  8744]], dtype=int64)

In [65]:
print(classification_report(y_test1,knn_prediction))
print("Accuracy:",metrics.accuracy_score(y_test1, knn_prediction))
metrics.confusion_matrix(y_test1, knn_prediction)

             precision    recall  f1-score   support

          0       0.68      0.81      0.74     75935
          1       0.39      0.24      0.29     37361

avg / total       0.59      0.62      0.60    113296

Accuracy: 0.6239584804406157


array([[61845, 14090],
       [28514,  8847]], dtype=int64)

# Naive Bayes

In [66]:
from sklearn.naive_bayes import BernoulliNB
nb= BernoulliNB()
nb.fit(x_train, y_train)
nb_prediction= nb.predict(x_test)

In [68]:
from sklearn.naive_bayes import BernoulliNB
nb= BernoulliNB()
nb.fit(x_train1, y_train1)
nb_prediction= nb.predict(x_test1)

In [69]:
print(classification_report(y_test,nb_prediction))
print("Accuracy:",metrics.accuracy_score(y_test, nb_prediction))
metrics.confusion_matrix(y_test, nb_prediction)

             precision    recall  f1-score   support

          0       0.67      1.00      0.80     75803
          1       0.00      0.00      0.00     37493

avg / total       0.45      0.67      0.54    113296

Accuracy: 0.6690703996610649


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


array([[75803,     0],
       [37493,     0]], dtype=int64)

In [70]:
print(classification_report(y_test1,nb_prediction))
print("Accuracy:",metrics.accuracy_score(y_test1, nb_prediction))
metrics.confusion_matrix(y_test1, nb_prediction)

             precision    recall  f1-score   support

          0       0.67      1.00      0.80     75935
          1       0.00      0.00      0.00     37361

avg / total       0.45      0.67      0.54    113296

Accuracy: 0.6702354893376642


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


array([[75935,     0],
       [37361,     0]], dtype=int64)

# Confusion Matrices

In [71]:
metrics.confusion_matrix(y_test, logistic_prediction)

array([[71469,  4334],
       [35275,  2218]], dtype=int64)

In [72]:
metrics.confusion_matrix(y_test1, logistic_prediction)

array([[73314,  2621],
       [33430,  3931]], dtype=int64)

In [73]:
metrics.confusion_matrix(y_test, knn_prediction)

array([[60501, 15302],
       [29858,  7635]], dtype=int64)

In [74]:
metrics.confusion_matrix(y_test1, knn_prediction)

array([[61845, 14090],
       [28514,  8847]], dtype=int64)

In [75]:
metrics.confusion_matrix(y_test, nb_prediction)

array([[75803,     0],
       [37493,     0]], dtype=int64)

In [76]:
metrics.confusion_matrix(y_test1, nb_prediction)

array([[75935,     0],
       [37361,     0]], dtype=int64)

# Conclusion

In [ ]:
#Logistic regression fetches the best results with an accuracy of 95.1%. This is because, Logitic regression works well with Yes/No scenarios. 